"""Second  migration

Revision ID: d67ae153c4cd
Revises: a02ff0eb5734
Create Date: 2023-08-21 17:00:58.324728

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd67ae153c4cd'
down_revision = 'a02ff0eb5734'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
